# Python for Reserving

*This [article](https://institute-and-faculty-of-actuaries.github.io/mlr-blog/post/foundations/2025-02-python/) was written by Vikram Suresh and originally published on 16 February 2025.*

For an introduction to Python in actuarial science, the [Actuaries' Analytic Cookbook](https://actuariesinstitute.github.io/cookbook/docs/) (which is an initiative of the Young Data Analytics Working Group, a working group within the [Australian Actuaries Institute](https://actuaries.asn.au/) is a great place to start.

In many of our blogs, particularly those focussing on deep learning, the code uses various packages, such as PyTorch, scikit-learn, Numpy and Pandas - a number of which are introduced in the aforementioned Cookbook. For example, PyTorch is a popular package for neural networks.

Instructions on how to install the packages and set up Python can be found on the Cookbook's [Setting up your environment](https://actuariesinstitute.github.io/cookbook/docs/getting_started.html) page. You can then start working through some of the Cookbook articles, or posts on our website.

Furthermore, our [online book](https://mlrwp.github.io/mlrwp-book/) which collects our blog posts may also be of interest. We will be updating this later in the year to include our recent series of blogs on using deep learning for reserving, but in the meantime check out [this post](https://institute-and-faculty-of-actuaries.github.io/mlr-blog/post/research/icnn-2024-02-covering/) for an overview.

## About the author

-   [Vikram Suresh](https://institute-and-faculty-of-actuaries.github.io/mlr-blog/authors/vsuresh/)
